/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ExperienciaRouteImport } from './routes/experiencia'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CertificadosRouteImport } from './routes/certificados'
import { Route as AtividadeRouteImport } from './routes/atividade'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ProjetosProjectIdRouteImport } from './routes/projetos.$projectId'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaRoute = ExperienciaRouteImport.update({
  id: '/experiencia',
  path: '/experiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadosRoute = CertificadosRouteImport.update({
  id: '/certificados',
  path: '/certificados',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadeRoute = AtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosProjectIdRoute = ProjetosProjectIdRouteImport.update({
  id: '/projetos/$projectId',
  path: '/projetos/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atividade': typeof AtividadeRoute
  '/certificados': typeof CertificadosRoute
  '/contato': typeof ContatoRoute
  '/experiencia': typeof ExperienciaRoute
  '/sobre': typeof SobreRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atividade': typeof AtividadeRoute
  '/certificados': typeof CertificadosRoute
  '/contato': typeof ContatoRoute
  '/experiencia': typeof ExperienciaRoute
  '/sobre': typeof SobreRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atividade': typeof AtividadeRoute
  '/certificados': typeof CertificadosRoute
  '/contato': typeof ContatoRoute
  '/experiencia': typeof ExperienciaRoute
  '/sobre': typeof SobreRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atividade'
    | '/certificados'
    | '/contato'
    | '/experiencia'
    | '/sobre'
    | '/projetos/$projectId'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atividade'
    | '/certificados'
    | '/contato'
    | '/experiencia'
    | '/sobre'
    | '/projetos/$projectId'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/atividade'
    | '/certificados'
    | '/contato'
    | '/experiencia'
    | '/sobre'
    | '/projetos/$projectId'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtividadeRoute: typeof AtividadeRoute
  CertificadosRoute: typeof CertificadosRoute
  ContatoRoute: typeof ContatoRoute
  ExperienciaRoute: typeof ExperienciaRoute
  SobreRoute: typeof SobreRoute
  ProjetosProjectIdRoute: typeof ProjetosProjectIdRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencia': {
      id: '/experiencia'
      path: '/experiencia'
      fullPath: '/experiencia'
      preLoaderRoute: typeof ExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificados': {
      id: '/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof CertificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividade': {
      id: '/atividade'
      path: '/atividade'
      fullPath: '/atividade'
      preLoaderRoute: typeof AtividadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$projectId': {
      id: '/projetos/$projectId'
      path: '/projetos/$projectId'
      fullPath: '/projetos/$projectId'
      preLoaderRoute: typeof ProjetosProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtividadeRoute: AtividadeRoute,
  CertificadosRoute: CertificadosRoute,
  ContatoRoute: ContatoRoute,
  ExperienciaRoute: ExperienciaRoute,
  SobreRoute: SobreRoute,
  ProjetosProjectIdRoute: ProjetosProjectIdRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
